### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kimhs950627** [maju116/sauron#30]
I tried to install the sauron package but I got the HTTP 404 error.. I literally copied your installation code. Kernel says : "HTTP error 404, No commit found for the ref master".

**Comment by maju116** [comment]
@kimhs950627 I just run `remotes::install_github("maju116/sauron")` and it works fine. From your error i see that you're trying to connect to `master` branch which not exist, you should use `main` branch. Try: `remotes::install_github("maju116/sauron", ref = "main")`

**Comment by kimhs950627** [comment]
OMG thank you now it's working
Thanks for this amazing package!
Also plz check the platypus package issues~

**Comment by maju116** [comment]
@kimhs950627 Thank yo very much!

Yes, I know I have to go back to `platypus`, this year was very challenging for me but soon I will go back to it :)
